[package]
name = "reorderable_list_with_gtk4"
version = "0.1.0"
edition = "2021"

[dependencies]
glib-sys = "0.17.4"
gtk = { version = "0.7", package = "gtk4", features = ["v4_12"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

